color: null
fieldLayouts:
  58ddc97d-9694-4104-a136-b6344987e1b6:
    cardView:
      - 'layoutElement:089ab2ac-9335-40c2-9827-f4dd1baca5dc'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-18T07:59:55+00:00'
            elementCondition: null
            fieldUid: 35b67fb3-4bdb-470f-a686-3d46c5cd5f96 # Builder: Content - Image - Image
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cd02812-349c-46d5-a4b7-57700a221566
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5e8a312e-45d0-491c-924d-84d96af3b270
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-18T07:59:55+00:00'
            elementCondition: null
            fieldUid: 9b73b533-898f-4f77-a500-37ea0be0afc7 # Builder: Content - Image - Show Image Caption
            handle: showImageCaption
            includeInCards: true
            instructions: null
            label: 'Show Image Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 089ab2ac-9335-40c2-9827-f4dd1baca5dc
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-03-27T16:24:46+00:00'
            elementCondition: null
            fieldUid: 7059a4d1-a4a2-4648-981e-d9398d6ae878 # Builder: Content - Image - Position Image Caption
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image Caption Position'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 519301be-7eab-4c7c-ba1f-3033706a81c9
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-18T07:59:55+00:00'
            elementCondition: null
            fieldUid: 70bc887b-faf2-45c7-b4bc-4299acd343da # Builder: Content - Image - Image Ratio
            handle: imageRatio
            includeInCards: false
            instructions: null
            label: 'Image Ratio'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0fb63ad-8f84-4caf-a7b6-c0e44deeae12
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-18T07:59:55+00:00'
            elementCondition: null
            fieldUid: 1be86da8-5273-40c6-ba88-718f5c32a6c3 # Builder: Content - Image - Image Width
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image Width'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 744a7c6f-6d25-4c12-8d70-9a8752b5f5f6
            userCondition: null
            warning: null
            width: 50
        name: Settings
        uid: 75c160e7-8471-441b-ba57-883694ddafba
        userCondition: null
handle: blockImage
hasTitleField: false
icon: null
name: Image
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
