color: null
fieldLayouts:
  b395a185-0801-4abb-aa25-3b0f0989bafa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-21T09:47:38+00:00'
            elementCondition: null
            fieldUid: 1516a801-6243-468d-b8e2-479085458faa # Text: Custom Title
            handle: textTitle
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0cad1bd-3de5-4a08-8fde-efe85c0e1ca2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-21T09:47:38+00:00'
            elementCondition: null
            fieldUid: d4cabad1-1cae-4a1e-a914-c38d9f1a813a # Builder: Content - Text - Text
            handle: textDescription
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5fcb48a-58df-413e-b8be-38961f71927b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-21T09:47:38+00:00'
            elementCondition: null
            fieldUid: 7fc64a2a-b955-454f-a41f-e61c5048ccb1 # Builder: Content - Entries
            handle: null
            includeInCards: false
            instructions: null
            label: Entries
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6549af1c-fa57-43ff-98e7-0fe79d4df01f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 44e23258-069c-4f0f-a39f-0156c8d56d06
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-21T09:47:38+00:00'
            elementCondition: null
            fieldUid: 25e45cda-5ba7-4493-bd27-25459a06863b # Builder: Content - View Mode
            handle: null
            includeInCards: false
            instructions: null
            label: 'View Mode'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1e051e7-60ea-4c9d-84ca-871a995a03f8
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: e9ae4af6-12dc-4a41-b409-361fcad05170
        userCondition: null
handle: blockEntries
hasTitleField: false
icon: null
name: Entries
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
