color: null
fieldLayouts:
  8802607c-be5b-4515-9f3e-1c16b95b4f93:
    cardView:
      - 'layoutElement:63c1f282-2328-45ef-b232-96d46f8c881d'
      - section
      - 'layoutElement:27918bbf-868d-4d1a-9c50-7fbbfbb917c1'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-21T09:42:47+00:00'
            elementCondition: null
            fieldUid: 1516a801-6243-468d-b8e2-479085458faa # Text: Custom Title
            handle: textTitle
            includeInCards: true
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27918bbf-868d-4d1a-9c50-7fbbfbb917c1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-21T09:42:47+00:00'
            elementCondition: null
            fieldUid: d4cabad1-1cae-4a1e-a914-c38d9f1a813a # Builder: Content - Text - Text
            handle: textDescription
            includeInCards: true
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63c1f282-2328-45ef-b232-96d46f8c881d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-21T09:42:47+00:00'
            elementCondition: null
            fieldUid: 772d842d-de0a-4d5c-a008-310a766ace70 # Builder: Content - Channel - Selection
            handle: null
            includeInCards: false
            instructions: null
            label: Channel
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba9c7a65-0052-4de5-82c2-12ff037bf85a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0c06282f-edb4-462a-87e5-3559a7a2aa1a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-21T09:42:47+00:00'
            elementCondition: null
            fieldUid: 25e45cda-5ba7-4493-bd27-25459a06863b # Builder: Content - View Mode
            handle: null
            includeInCards: false
            instructions: null
            label: 'View Mode'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba943dc9-6a7c-44c6-a01b-61dff75cf554
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-21T09:42:47+00:00'
            elementCondition: null
            fieldUid: f63c3988-00f8-4310-8741-5408a416230e # Builder: Content - Entry Limit
            handle: null
            includeInCards: false
            instructions: null
            label: Limit
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12a4d26b-3ebe-45c0-834e-ad00ee5a2f7a
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: c75f50bf-1f99-45c5-a0b4-62d0bfbbb595
        userCondition: null
handle: blockChannel
hasTitleField: false
icon: null
name: Channel
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
