color: null
fieldLayouts:
  d326fa3e-ed09-41a5-8055-f3f253f6d9b6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-28T10:43:34+00:00'
            elementCondition: null
            fieldUid: be45c3e2-5e9f-491e-a000-94d95c4fa20b # Builder: Content - Code - Snippet
            handle: null
            includeInCards: false
            instructions: null
            label: 'Embed Code'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f071584c-b026-48a4-b552-0464724a59be
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-28T10:43:34+00:00'
            elementCondition: null
            fieldUid: 1be86da8-5273-40c6-ba88-718f5c32a6c3 # Builder: Content - Image - Image Width
            handle: contentWidth
            includeInCards: false
            instructions: null
            label: Width
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ef6aee9-0e32-4dff-b70e-5534dfb3e95c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4e287a9e-1adc-489e-a2cb-db42ed6de194
        userCondition: null
handle: blockEmbed
hasTitleField: false
icon: null
name: Embed
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
