color: null
fieldLayouts:
  e22d570c-156e-4591-a91a-2af67c7ed22b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-18T07:59:55+00:00'
            elementCondition: null
            fieldUid: 53f0660a-f06b-4b2d-b342-1869c5c65538 # Builder: Content - Quote - Quote
            handle: null
            includeInCards: true
            instructions: null
            label: Quote
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd2dc568-fec5-4384-b6d0-dc26b5dd7b34
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-18T07:59:55+00:00'
            elementCondition: null
            fieldUid: c40b8b5e-0ccb-4d0d-9eee-bd24ac9209b0 # Builder: Content - Quote - Source
            handle: null
            includeInCards: false
            instructions: null
            label: Source
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fcea238-ad3d-4958-9762-4a3f7c2cb1e9
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-18T07:59:55+00:00'
            elementCondition: null
            fieldUid: 75b6f580-613f-42ae-aa23-2d5fb22ff3da # Builder: Content - Quote - Source Subline
            handle: null
            includeInCards: false
            instructions: null
            label: 'Source Subline'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81e0a6bb-2f47-4d2f-b800-a0a2651a916f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-18T07:59:55+00:00'
            elementCondition: null
            fieldUid: e11e03f7-19c1-45c3-935e-1994a7ce7d26 # Builder: Content - Quote - Source Url
            handle: null
            includeInCards: false
            instructions: null
            label: 'Source Url'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25bfda37-86b0-4276-ae59-e34d406c5eba
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 8e061a5e-d78f-48e7-b026-09c9f9a49a67
        userCondition: null
handle: blockQuote
hasTitleField: false
icon: null
name: Quote
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
