color: null
fieldLayouts:
  6c449cd7-ebc2-4ce6-be61-1e8c90cb176b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-18T07:59:55+00:00'
            elementCondition: null
            fieldUid: 75195ab8-b7c4-4dca-b807-ef8a042ef5a9 # Builder: Content - Image Grid - Images
            handle: null
            includeInCards: false
            instructions: null
            label: Images
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d10b279e-4bce-49cf-90fd-0a2fae06d537
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 56042e3e-7a7b-4a4c-9222-63e004682c9b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-18T09:03:59+00:00'
            elementCondition: null
            fieldUid: b77696b8-7875-400d-a2a2-2156504864f0 # Builder: Content - Images - View Mode
            handle: null
            includeInCards: false
            instructions: null
            label: 'View Mode'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9493f70-ec9e-43c8-bbec-a0d065d13780
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-18T07:59:55+00:00'
            elementCondition: null
            fieldUid: 62883121-63a2-4e5c-a6f3-4855cf64df2c # Builder: Content - Image Grid - Image Transform
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image Ratio'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 721a9d99-a7c1-4462-b772-b18fadab09e8
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-18T07:59:55+00:00'
            elementCondition: null
            fieldUid: e0e9e510-46ff-45aa-aa46-700b325bb911 # Builder: Content - Image Grid - Show Image Caption
            handle: null
            includeInCards: false
            instructions: null
            label: 'Show Image Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9eae0590-a0dc-4c71-8d19-af63a55af1bd
            userCondition: null
            warning: null
            width: 50
        name: Settings
        uid: f3371511-8ac1-4bc0-8129-f45046b0c06f
        userCondition: null
handle: blockImages
hasTitleField: false
icon: null
name: Images
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
