allowPublicRegistration: false
deactivateByDefault: false
defaultGroup: ''
photoSubpath: '{username}'
photoVolumeUid: 8dda1580-81a2-49f5-9dd2-ed1e2eb03fc6 # Users
requireEmailVerification: true
validateOnPublicRegistration: false
