isPublic: true
name: 'Public Schema'
scope:
  - 'sites.8153a2df-373f-4aac-9a92-d52292c9f1aa:read' # Baukasten
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'volumes.6c5fc0dd-cf56-48d8-8af8-88abe763b970:read' # Files
  - 'volumes.f1b38495-8096-48fa-9b78-0da345e3295c:read' # Images
  - 'volumes.77c74b5c-6bbb-41a7-b166-c6b158a3cc7f:read' # Template Images
  - 'volumes.8dda1580-81a2-49f5-9dd2-ed1e2eb03fc6:read' # Users
  - 'usergroups.everyone:read'
  - 'formieforms.all:read'
  - 'formieforms.56e2dea4-d25e-496d-b053-48387e824b07:read'
  - 'formiesubmissions.all:read'
  - 'formiesubmissions.56e2dea4-d25e-496d-b053-48387e824b07:read'
  - 'navigationnavs.all:read'
  - 'navigationnavs.7eb1a718-0679-4fda-b656-9bfdf55a2025:read' # Navigation Main
  - 'seomatic.all:read'
  - 'sections.5d0f7961-203c-4008-a55a-6a7d35e7a37a:read' # Home
  - 'sections.3547e7b4-f3fb-4cf4-9d29-9f12dfa94594:read' # News
  - 'sections.b0207f48-be48-49ab-a759-1ff51f232df3:read' # Pages
  - 'sections.e5172a18-ed16-4229-89ca-fc0dc776597a:read' # Error Pages
