columnSuffix: null
handle: builderContent
instructions: null
name: 'Builder: Content'
searchable: true
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - b3022ef5-7f1b-49d7-976d-5d5be501c1f1 # Section
    -
      __assoc__:
        -
          - uid
          - 0895deae-97b1-455c-b5c9-5910bd9cd114 # Headline : Text
        -
          - name
          - 'Content: Headline Text Block'
    -
      __assoc__:
        -
          - uid
          - 7b3b13e0-e20d-4d51-b0ae-832300f45234 # Text
        -
          - name
          - 'Content: Text'
    -
      __assoc__:
        -
          - uid
          - 3497ad65-5e4c-43cb-b469-c3e4b3d80343 # Text : Image
        -
          - name
          - 'Content: Text Image Block'
    -
      __assoc__:
        -
          - uid
          - fa02ff5a-1741-4417-8c8f-b72b954dd4fd # Quote
        -
          - name
          - 'Content: Quote'
    -
      __assoc__:
        -
          - uid
          - 29ca425f-8a7a-4865-a934-9e7ffa64d538 # Channel
        -
          - name
          - 'Collection: Channel'
    -
      __assoc__:
        -
          - uid
          - b2dfe7b0-0d6e-4678-b023-020fad0eb696 # Content
        -
          - name
          - 'Collection: Content'
    -
      __assoc__:
        -
          - uid
          - b502cc32-1a21-49f2-9fe6-f24265e51a45 # Entries
        -
          - name
          - 'Collection: Entries'
    -
      __assoc__:
        -
          - uid
          - e3c7bdf5-9e45-4977-ba11-1e2c4b57644e # Divider
        -
          - name
          - 'Layout: Divider'
    -
      __assoc__:
        -
          - uid
          - 92963d20-e763-4d2e-a367-9e543dfde522 # Spacer
        -
          - name
          - 'Layout: Spacer'
    -
      __assoc__:
        -
          - uid
          - 4ad1b3a9-e348-4c05-8f2f-eb0ef86e4073 # Embed
        -
          - name
          - 'Media: Embed'
    -
      __assoc__:
        -
          - uid
          - 295738c1-951d-4b8c-b5cd-83d71a85d7e8 # Image
        -
          - name
          - 'Media: Image'
    -
      __assoc__:
        -
          - uid
          - 5c9f2ce6-f780-4ea6-a50c-539a252aec94 # Images
        -
          - name
          - 'Media: Images'
    -
      __assoc__:
        -
          - uid
          - 7b23a4a8-a6f8-43c4-b12c-326d089176ad # Video
        -
          - name
          - 'Media: Video'
    -
      __assoc__:
        -
          - uid
          - f3e1a215-a60f-4d6a-8897-e1a80a40c6cd # Code
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
