columnSuffix: null
handle: imagesViewMode
instructions: null
name: 'Builder: Content - Images - View Mode'
searchable: false
settings:
  cachedOptions: true
  customOptions: false
  element: null
  genError: ''
  json: ''
  template: _super-dynamic-fields/images-view-mode.json
  templateData: ''
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SueprDynamicDropdownField
