columnSuffix: null
handle: sectionBackgroundColor
instructions: null
name: 'Builder: Content - Section - Section Background Color'
searchable: false
settings:
  cachedOptions: true
  customOptions: false
  element: null
  genError: ''
  json: ''
  template: _super-dynamic-fields/background-color-section.json
  templateData: ''
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SueprDynamicDropdownField
