columnSuffix: null
handle: sectionPaddingVertical
instructions: null
name: 'Builder: Content - Section - Section Padding Vertical'
searchable: false
settings:
  cachedOptions: true
  customOptions: false
  element: null
  genError: null
  json: ''
  template: _super-dynamic-fields/spacing-padding-vertical.json
  templateData: null
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SueprDynamicDropdownField
