columnSuffix: null
handle: spaceBetweenBlocks
instructions: null
name: 'Builder: Content - Section - Space Between Blocks'
searchable: false
settings:
  cachedOptions: true
  customOptions: false
  element: null
  genError: ''
  json: ''
  template: _super-dynamic-fields/spacing-between-y.json
  templateData: ''
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SueprDynamicDropdownField
