dateModified: 1743412945
elementSources:
  craft\elements\Asset:
    -
      key: 'volume:6c5fc0dd-cf56-48d8-8af8-88abe763b970' # Files
      type: native
    -
      disabled: false
      key: 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      tableAttributes:
        - filename
        - size
        - dateModified
        - uploader
        - link
        - imageSize
      type: native
    -
      disabled: false
      key: 'volume:77c74b5c-6bbb-41a7-b166-c6b158a3cc7f' # Template Images
      tableAttributes:
        - filename
        - size
        - dateModified
        - uploader
        - link
        - imageSize
      type: native
    -
      key: 'volume:8dda1580-81a2-49f5-9dd2-ed1e2eb03fc6' # Users
      type: native
    -
      key: 'folder:c8e15363-b103-4fd2-b6e4-097752fa2cef'
      type: native
email:
  fromEmail: $SYSTEM_MAIL
  fromName: $SITE_NAME
  replyToEmail: $REPLY_MAIL
  template: null
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
fs:
  files:
    hasUrls: true
    name: Files
    settings:
      path: '@webroot/assets/files'
    type: craft\fs\Local
    url: '@assetsUrl/files/'
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/assets/images'
    type: craft\fs\Local
    url: '@assetsUrl/images/'
  templateImages:
    hasUrls: true
    name: 'Template Images'
    settings:
      path: '@webroot/assets/templateImages'
    type: craft\fs\Local
    url: '@assetsUrl/templateImages/'
  transforms:
    hasUrls: true
    name: Transforms
    settings:
      path: '@webroot/assets/transforms'
    type: craft\fs\Local
    url: '@assetsUrl/transforms/'
  users:
    hasUrls: true
    name: Users
    settings:
      path: '@webroot/assets/users'
    type: craft\fs\Local
    url: '@assetsUrl/users/'
meta:
  __names__:
    0a7dd988-f4db-40b7-8112-6f6fc7c4fb54: 'Builder: Content - Text : Image - Text' # Builder: Content - Text : Image - Text
    0dc851b0-a289-4c50-be8d-0c055b270ee8: 'Asset: Entry Image' # Asset: Entry Image
    1b37c439-5a32-4e8f-8019-7f6a94593419: 'Builder: Content - Spacer - Spacer Variant' # Builder: Content - Spacer - Spacer Variant
    1be86da8-5273-40c6-ba88-718f5c32a6c3: 'Builder: Content - Image - Image Width' # Builder: Content - Image - Image Width
    1c94bbf7-46b0-46e4-a699-b4eef42994a0: 'Text: Editor Simple' # Text: Editor Simple
    2bc1feee-cfc8-48ee-bace-f101e7f41ac9: Default # Default
    2f642060-4792-41cb-a427-083aabeba231: 'Content Builder' # Content Builder
    3ac3bfdf-e50b-46e3-abb9-cef4bffab4a0: 'Builder: Content - Video - Autoplay' # Builder: Content - Video - Autoplay
    3cc5cb1b-b446-4459-b458-bab6c01226a5: 'Builder: Content - Section - Section Anchor' # Builder: Content - Section - Section Anchor
    4a25e574-679a-4d01-8e8b-d5927129ce33: 'Builder: Content - Video - Loop' # Builder: Content - Video - Loop
    4ad1b3a9-e348-4c05-8f2f-eb0ef86e4073: Embed # Embed
    4f69dba7-71a6-416e-a773-1d8230568aff: 'Content Matrix' # Content Matrix
    5c9f2ce6-f780-4ea6-a50c-539a252aec94: Images # Images
    5d0f7961-203c-4008-a55a-6a7d35e7a37a: Home # Home
    6a90dae3-938c-47e6-8e36-6b1d6be92d63: 'Builder: Content - Text : Image - Show Image Caption' # Builder: Content - Text : Image - Show Image Caption
    6c5fc0dd-cf56-48d8-8af8-88abe763b970: Files # Files
    6d94dcc4-6ec1-45b4-8c86-e53cee842b11: 'Overview News' # Overview News
    6f4a3e01-23de-4313-8109-00a430317d11: 'Rich Text Default' # Rich Text Default
    7b3b13e0-e20d-4d51-b0ae-832300f45234: Text # Text
    7b23a4a8-a6f8-43c4-b12c-326d089176ad: Video # Video
    7e8fd607-0b56-4196-9e02-76ebba9ad7bd: New # New
    7eb1a718-0679-4fda-b656-9bfdf55a2025: 'Navigation Main' # Navigation Main
    7fc64a2a-b955-454f-a41f-e61c5048ccb1: 'Builder: Content - Entries' # Builder: Content - Entries
    8ced5be5-13b2-483f-8db9-aab9757aad21: Error # Error
    8d272b11-c1b4-4fc3-95c8-9d94fa513795: 'Text: Links' # Text: Links
    8dda1580-81a2-49f5-9dd2-ed1e2eb03fc6: Users # Users
    9a8fffce-3c28-4326-8f7a-e31d2f6cc04b: 'Builder: Content - Section - Section Background Color' # Builder: Content - Section - Section Background Color
    9b73b533-898f-4f77-a500-37ea0be0afc7: 'Builder: Content - Image - Show Image Caption' # Builder: Content - Image - Show Image Caption
    9cb7ea0d-8dd4-4298-ac6c-ab6c0efbe6ba: 'Builder: Content - Code - Snippet Name' # Builder: Content - Code - Snippet Name
    9f7c46cf-d2fd-4aff-b605-76d2127e9368: Settings # Settings
    25e45cda-5ba7-4493-bd27-25459a06863b: 'Builder: Content - View Mode' # Builder: Content - View Mode
    29ca425f-8a7a-4865-a934-9e7ffa64d538: Channel # Channel
    34c48f87-e4f0-4c33-aac4-73de400425f7: 'Contact: E-Mail' # Contact: E-Mail
    35b67fb3-4bdb-470f-a686-3d46c5cd5f96: 'Builder: Content - Image - Image' # Builder: Content - Image - Image
    53f0660a-f06b-4b2d-b342-1869c5c65538: 'Builder: Content - Quote - Quote' # Builder: Content - Quote - Quote
    63bd200d-3882-4788-a8ba-528452521d6c: 'Builder: Content - Video - Video Provider' # Builder: Content - Video - Video Provider
    63e3914d-ee70-44c2-9dc3-91551f47c54f: 'Text: Editor Default' # Text: Editor Default
    70bc887b-faf2-45c7-b4bc-4299acd343da: 'Builder: Content - Image - Image Ratio' # Builder: Content - Image - Image Ratio
    74b87138-1475-47c2-a9dd-63baa78dd5f5: 'Builder: Content - Section - Space Between Blocks' # Builder: Content - Section - Space Between Blocks
    74c3cd4f-b565-4fb4-879e-72022774f93c: 'Builder: Content - Images - Variant' # Builder: Content - Images - Variant
    74eb36ae-7a26-4e7d-b454-990ec52617f0: 'Builder: Content' # Builder: Content
    75b6f580-613f-42ae-aa23-2d5fb22ff3da: 'Builder: Content - Quote - Source Subline' # Builder: Content - Quote - Source Subline
    77c74b5c-6bbb-41a7-b166-c6b158a3cc7f: 'Template Images' # Template Images
    81d0ea50-f7e1-4eff-8138-2a06ffbfae86: Home # Home
    98f7a455-6764-4b7d-8d19-405bdcc42228: 'Builder: Content - Text : Image - Image Ratio' # Builder: Content - Text : Image - Image Ratio
    210de09a-f6c8-42dd-b4d6-c1c00e7d0b82: 'Builder: Content - Text : Image - Image Position' # Builder: Content - Text : Image - Image Position
    359d175b-2fe0-421b-959a-16ca87c71044: Contact # Contact
    419ebfbb-8723-48db-ae89-10adf52cdf11: 'Text: Source' # Text: Source
    772d842d-de0a-4d5c-a008-310a766ace70: 'Builder: Content - Channel - Selection' # Builder: Content - Channel - Selection
    0895deae-97b1-455c-b5c9-5910bd9cd114: 'Headline : Text' # Headline : Text
    1516a801-6243-468d-b8e2-479085458faa: 'Text: Custom Title' # Text: Custom Title
    3497ad65-5e4c-43cb-b469-c3e4b3d80343: 'Text : Image' # Text : Image
    3547e7b4-f3fb-4cf4-9d29-9f12dfa94594: News # News
    7059a4d1-a4a2-4648-981e-d9398d6ae878: 'Builder: Content - Image - Position Image Caption' # Builder: Content - Image - Position Image Caption
    8153a2df-373f-4aac-9a92-d52292c9f1aa: Baukasten # Baukasten
    8780cb03-c9ea-4482-ab85-3e541453b50f: 'Text: Source Url' # Text: Source Url
    9005a655-4d9f-46b4-8c33-aadba34b6112: 'Social Sharing Facebook' # Social Sharing Facebook
    45510f13-91d2-479f-9ff2-68dd09ab6643: 'Text: Entry Description' # Text: Entry Description
    68109da0-245f-4b21-b040-b7f4385e618e: 'Builder: Content - Video - Video Width' # Builder: Content - Video - Video Width
    75195ab8-b7c4-4dca-b807-ef8a042ef5a9: 'Builder: Content - Images - Images' # Builder: Content - Images - Images
    92963d20-e763-4d2e-a367-9e543dfde522: Spacer # Spacer
    295738c1-951d-4b8c-b5cd-83d71a85d7e8: Image # Image
    644167c0-ab2a-4f9d-9b2b-09f5a6556ef3: 'Public Schema' # Public Schema
    8084749f-eb17-4a45-ab26-e97ba0e1d9de: Adress # Adress
    62883121-63a2-4e5c-a6f3-4855cf64df2c: 'Builder: Content - Images - Image Ratio' # Builder: Content - Images - Image Ratio
    aa7883a4-2cce-4316-85f3-ec6ea59402ec: 'Builder: Content - Section - Section Padding Vertical' # Builder: Content - Section - Section Padding Vertical
    aac37142-e533-49aa-8665-b8cc6360e98b: 'Text: Caption' # Text: Caption
    b0207f48-be48-49ab-a759-1ff51f232df3: Pages # Pages
    b2dfe7b0-0d6e-4678-b023-020fad0eb696: Content # Content
    b81cb731-dd6f-4055-9c6d-2f076a727a27: 'Builder: Content - Text : Image - Image' # Builder: Content - Text : Image - Image
    b502cc32-1a21-49f2-9fe6-f24265e51a45: Entries # Entries
    b3022ef5-7f1b-49d7-976d-5d5be501c1f1: Section # Section
    b77696b8-7875-400d-a2a2-2156504864f0: 'Builder: Content - Images - View Mode' # Builder: Content - Images - View Mode
    be2e7784-2696-4ab4-b908-f92381235f97: 'Contact: Phone' # Contact: Phone
    be45c3e2-5e9f-491e-a000-94d95c4fa20b: 'Builder: Content - Code - Snippet' # Builder: Content - Code - Snippet
    c40b8b5e-0ccb-4d0d-9eee-bd24ac9209b0: 'Builder: Content - Quote - Source' # Builder: Content - Quote - Source
    c41504c5-f329-4495-9893-6237d54835c1: 'Builder: Content - Content Blocks' # Builder: Content - Content Blocks
    cf2f33c5-65b1-4ffe-ad64-c430610bc777: 'Builder: Content - Text - Headline Size' # Builder: Content - Text - Headline Size
    cf5b11e3-a6d6-430f-991f-9b78f9e4dd7f: 'Builder: Content - Code - Snippet collapsed' # Builder: Content - Code - Snippet collapsed
    d4cabad1-1cae-4a1e-a914-c38d9f1a813a: 'Builder: Content - Text - Text' # Builder: Content - Text - Text
    d29e8520-ab62-4c8f-bda2-61868797c1ca: 'SEO: SEOmatic' # SEO: SEOmatic
    da086ad5-4309-4b01-8796-d52bf2c3700c: 'Social Media Channels' # Social Media Channels
    e0e9e510-46ff-45aa-aa46-700b325bb911: 'Builder: Content - Images - Show Image Caption' # Builder: Content - Images - Show Image Caption
    e3c7bdf5-9e45-4977-ba11-1e2c4b57644e: Divider # Divider
    e8b10d27-be46-4108-9bf5-3a8711280165: 'Rich Text Simple' # Rich Text Simple
    e11e03f7-19c1-45c3-935e-1994a7ce7d26: 'Builder: Content - Quote - Source Url' # Builder: Content - Quote - Source Url
    e5172a18-ed16-4229-89ca-fc0dc776597a: 'Error Pages' # Error Pages
    e9486b85-fd5e-40c8-851b-a6b0133e1f88: 'Builder: Content - Video - Video Id' # Builder: Content - Video - Video Id
    f084e099-613d-4405-b600-f4be12d3509b: 'Builder: Content - Divider - Divider Variant' # Builder: Content - Divider - Divider Variant
    f1b38495-8096-48fa-9b78-0da345e3295c: Images # Images
    f3e1a215-a60f-4d6a-8897-e1a80a40c6cd: Code # Code
    f63c3988-00f8-4310-8741-5408a416230e: 'Builder: Content - Entry Limit' # Builder: Content - Entry Limit
    f4959e03-fec0-4b1c-887e-5301a5f66742: 'Social Sharing Twitter' # Social Sharing Twitter
    fa02ff5a-1741-4417-8c8f-b72b954dd4fd: Quote # Quote
    fb701216-3e80-4e6d-99d4-2e5f70561e22: 'News Detail' # News Detail
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_BLITZ
    schemaVersion: 5.9.0
    settings:
      integrations:
        - putyourlightson\blitz\drivers\integrations\CommerceIntegration
  blur-hash:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  codefield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-clearcache:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: ''
      cssFile: /dist/css/controlPanelCss.css
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  elements-panel:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  empty-coalesce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_FORMIE
    schemaVersion: 3.4.8
    settings:
      ajaxTimeout: 10
      captchas:
        __assoc__:
          -
            - recaptcha
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Recaptcha
                -
                  - enabled
                  - false
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - recaptcha
                      -
                        - secretKey
                        - ''
                      -
                        - siteKey
                        - ''
                      -
                        - type
                        - v3
                      -
                        - size
                        - normal
                      -
                        - theme
                        - light
                      -
                        - badge
                        - bottomright
                      -
                        - language
                        - en
                      -
                        - minScore
                        - '0.5'
          -
            - duplicate
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Duplicate
                -
                  - enabled
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - duplicate
          -
            - honeypot
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Honeypot
                -
                  - enabled
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - honeypot
          -
            - javascript
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Javascript
                -
                  - enabled
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - javascript
                      -
                        - minTime
                        - '10'
      defaultDateDisplayType: ''
      defaultDateTime: ''
      defaultDateValueOption: ''
      defaultEmailTemplate: ''
      defaultFileUploadVolume: ''
      defaultFormTemplate: ''
      defaultInstructionsPosition: below-input
      defaultLabelPosition: above-input
      defaultPage: forms
      enableCsrfValidationForGuests: true
      enableGatsbyCompatibility: false
      enableUnloadWarning: true
      maxIncompleteSubmissionAge: 30
      maxSentNotificationsAge: 30
      pluginName: Formie
      saveSpam: true
      sendEmailAlerts: false
      sentNotifications: true
      spamBehaviour: showSuccess
      spamBehaviourMessage: ''
      spamEmailNotifications: false
      spamKeywords: ''
      spamLimit: 1000
      useQueueForIntegrations: true
      useQueueForNotifications: true
  hyper:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_HYPER
    schemaVersion: 1.0.0
  image-resizer:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  imager-x:
    edition: pro
    enabled: true
    licenseKey: $PLUGIN_IMAGERX
    schemaVersion: 4.0.0
  matrixmate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_NAVIGATION
    schemaVersion: 2.1.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_SEOMATIC
    schemaVersion: 3.0.12
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: local
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: '1'
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 'null'
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: '1'
      truncateTitleTags: '1'
  sherlock:
    edition: lite
    enabled: true
    schemaVersion: 4.5.0
    settings:
      maxScans: false
      strictTransportSecurity:
        canFail: true
        threshold: 15552000
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  super-dynamic-fields:
    edition: standard
    enabled: true
    licenseKey: HWHCIWN81OICEM6JJHFF7TQF
    schemaVersion: 5.0.1
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: Baukasten
  retryDuration: null
  schemaVersion: 5.6.0.2
  timeZone: Europe/Berlin
